#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
----------------------------------------------------------------------
"

echo "Executing usermod..."
mkdir "/tmp/temphome"
usermod -d "/tmp/temphome" hotio
usermod -o -u "${PUID}" hotio
usermod -d "${CONFIG_DIR}" hotio
rm -rf "/tmp/temphome"
groupmod -o -g "${PGID}" hotio

echo "Applying permissions to ${CONFIG_DIR}"
chmod "=rwx" "${CONFIG_DIR}"
chown hotio:hotio "${CONFIG_DIR}"

echo "Applying permissions to /cache"
chmod "=rwx" "/cache"
chown hotio:hotio "/cache"

echo "Applying permissions to /logs"
chmod "=rwx" "/logs"
chown hotio:hotio "/logs"

if [[ ! -f "${CONFIG_DIR}/machine-id" ]]; then
    tr -dc 'a-f0-9' < /dev/urandom | fold -w 32 | head -n 1 > "${CONFIG_DIR}/machine-id"
    chown hotio:hotio "${CONFIG_DIR}/machine-id"
fi

if [[ ! -f "${CONFIG_DIR}/settings.json" ]]; then
    echo '{
        "listening_address"     : "0.0.0.0:3875",
        "log_directory"         : "/logs",
        "temporary_directory"   : "/cache"
    }' > "${CONFIG_DIR}/settings.json"
    chown hotio:hotio "${CONFIG_DIR}/settings.json"
fi

if [[ ! -f "${CONFIG_DIR}/duplicacy.json" ]]; then
    echo '{}' > "${CONFIG_DIR}/duplicacy.json"
    chown hotio:hotio "${CONFIG_DIR}/duplicacy.json"
fi
