#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

# shellcheck disable=SC2086
HOME="${APP_DIR}" redirect_cmd exec s6-setuidgid hotio "${APP_DIR}/duplicacy_web" ${ARGS}
