#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
----------------------------------------------------------------------
"

log_inf "Taking ownership of [/cache]."
find "/cache" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +

log_inf "Taking ownership of [/logs]."
find "/logs" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +

if [[ ! -f "${CONFIG_DIR}/machine-id" ]]; then
    tr -dc 'a-f0-9' < /dev/urandom | fold -w 32 | head -n 1 > "${CONFIG_DIR}/machine-id"
    find "${CONFIG_DIR}/machine-id" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi

if [[ ! -f "${CONFIG_DIR}/settings.json" ]]; then
    log_inf "Installing default [${CONFIG_DIR}/settings.json] file."
    echo '{
        "listening_address"     : "0.0.0.0:3875",
        "log_directory"         : "/logs",
        "temporary_directory"   : "/cache"
    }' > "${CONFIG_DIR}/settings.json"
    find "${CONFIG_DIR}/settings.json" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi

if [[ ! -f "${CONFIG_DIR}/duplicacy.json" ]]; then
    log_inf "Installing default [${CONFIG_DIR}/duplicacy.json] file."
    echo '{}' > "${CONFIG_DIR}/duplicacy.json"
    find "${CONFIG_DIR}/duplicacy.json" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
