#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/machine-id" ]]; then
    tr -dc 'a-f0-9' < /dev/urandom | fold -w 32 | head -n 1 > "${CONFIG_DIR}/machine-id"
    chown hotio:hotio "${CONFIG_DIR}/machine-id"
fi

if [[ ! -f "${CONFIG_DIR}/settings.json" ]]; then
    echo '{
        "listening_address"     : "0.0.0.0:3875",
        "log_directory"         : "/logs",
        "temporary_directory"   : "/cache"
    }' > "${CONFIG_DIR}/settings.json"
    chown hotio:hotio "${CONFIG_DIR}/settings.json"
fi

if [[ ! -f "${CONFIG_DIR}/duplicacy.json" ]]; then
    echo '{}' > "${CONFIG_DIR}/duplicacy.json"
    chown hotio:hotio "${CONFIG_DIR}/duplicacy.json"
fi
